name: Run Calendar Logic

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # આનાથી તમે જાતે પણ બટન દબાવીને રન કરી શકશો

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile and Run Kotlin Calendar
      run: |
        # કોટલીન કમ્પાઈલર ડાઉનલોડ કરવું
        sudo apt-get install kotlinc -y
        
        # બધી ફાઈલોને એકસાથે કમ્પાઈલ કરવી
        kotlinc src/main/kotlin/*.kt -include-runtime -d calendar.jar
        
        # પ્રોગ્રામ રન કરવો (આપણે એક નાની ટેસ્ટ લાઈન ઉમેરીશું)
        java -jar calendar.jar

